Rewrote this script to thoroughly check the burned CD with md5sum

diff --git a/cdcheck b/cdcheck
--- a/cdcheck
+++ b/cdcheck
@@ -1,16 +1,19 @@
-#! /bin/sh
+#! /bin/bash
 
-#--------------------------------------------------------------------------
-# Script to quickly check the contents of the inserted CD and then
-# umount it.
-#--------------------------------------------------------------------------
+# Script to thoroughly check the contents of a CD against the directory
+# it was burned from, using md5sum
 
-# Script to quickly display back the root dir of the CD in the 
-# drive and then umount it.
+md5Sums=$(mktemp --tmpdir --suffix=.md5 cdcheck-XXXX)
+optMount="/media/cd"
 
-CDDIR=/media/cd
+find . -type f | xargs md5sum | tee $md5Sums
 
-mount $CDDIR
-ls -lh $CDDIR
-umount $CDDIR
+mount $optMount
+pushd $optMount
 
+md5sum -c $md5Sums || echo "FAILED, THIS DISC IS PROBABLY BAD!"
+
+popd
+umount $optMount
+
+rm $md5Sums
