Changed 3-space indents to 2-space

diff --git a/mdconv b/mdconv
--- a/mdconv
+++ b/mdconv
@@ -5,11 +5,11 @@ basename=$(basename "$0")
 
 
 function usage {
-   cat <<USAGE
+  cat <<USAGE
 $basename - Convert Markdown to various formats using Pandoc
 
 usage:
-   $basename OUTPUT_FORMAT MARKDOWN_DOCUMENT
+  $basename OUTPUT_FORMAT MARKDOWN_DOCUMENT
 
 OUTPUT_FORMAT is one of: html, pdf
 
@@ -29,9 +29,9 @@ USAGE
 
 if [ $# -lt 2 ]
 then
-   echo "ERROR: Missing required arguments"
-   usage
-   exit 1
+  echo "ERROR: Missing required arguments"
+  usage
+  exit 1
 fi
 
 format="$1"
@@ -39,11 +39,11 @@ infile="$2"
 switches="-s"
 
 while true ; do
-   case "$format" in
-      html) break;;
-      pdf) switches="$switches -V geometry:margin=1in"; break;;
-      *) echo "ERROR: Unknown format"; usage; exit 1; break;;
-   esac
+  case "$format" in
+    html) break;;
+    pdf) switches="$switches -V geometry:margin=1in"; break;;
+    *) echo "ERROR: Unknown format"; usage; exit 1; break;;
+  esac
 done
 
 outfile="${infile%.*}.$format"
