Added arg parsing and -m/--margin switch
Added warn and die functions for error and other output handling.

Added args parsing code so we can introduce some switches. Part of this was
changing the usage from a function to a multiline string to be used by the warn
and die functions.

Added the -m/--margin switch for PDF output.

diff --git a/mdconv b/mdconv
--- a/mdconv
+++ b/mdconv
@@ -4,12 +4,15 @@
 basename=$(basename "$0")
 
 
-function usage {
-  cat <<USAGE
-$basename - Convert Markdown to various formats using Pandoc
+usage=$(cat <<USAGE
+Convert Markdown to various formats using Pandoc
 
 usage:
-  $basename OUTPUT_FORMAT MARKDOWN_DOCUMENT
+  $basename [OPTIONS] OUTPUT_FORMAT MARKDOWN_DOCUMENT
+
+options:
+  -m, --margin STR  Specify PDF margin measurement. Examples: '2cm' '1mm'. Default: '1cm'
+  -h, --help        This help information
 
 OUTPUT_FORMAT is one of: html, pdf
 
@@ -27,16 +30,54 @@ format and then:
 v1.2  2025-02-16  Dino Morelli <dino@ui3.info>
 
 USAGE
+)
+
+
+warn () {
+  echo "$basename:" "$@" >&2
+}
+
+
+die () {
+  rc="$1"
+  shift
+  warn "$@"
+  exit "$rc"
 }
 
 
 # arg parsing
 
+getoptResults=$(getopt --options m:h --longoptions margin:,help --name "$basename" -- "$@") \
+  || die 1 "$usage"
+
+# Note the quotes around "$getoptResults": they are essential!
+eval set -- "$getoptResults"
+
+optMargin="1cm"
+optHelp=false
+
+while true ; do
+  case "$1" in
+    -m|--margin) optMargin="$2"; shift 2;;
+    -h|--help) optHelp=true; shift;;
+    --) shift; break;;
+  esac
+done
+
+echo "detail of arguments"
+echo "optMargin: $optMargin"
+echo "optHelp: $optHelp"
+echo "number of remaining parameters: $#"
+echo "remaining parameters: $*"
+echo
+
+$optHelp && die 0 "$usage"
+
 if [ $# -lt 2 ]
 then
-  echo "ERROR: Missing required arguments"
-  usage
-  exit 1
+  warn "Incorrect number of ITEMs"
+  die 1 "$usage"
 fi
 
 format="$1"
@@ -58,12 +99,11 @@ while true ; do
       switches+=("--metadata lang=en-US")
       break;;
     pdf)
-      switches+=("--variable=geometry:margin=1cm")
+      switches+=("--variable=geometry:margin=${optMargin}")
       break;;
     *)
-      echo "ERROR: Unknown format"
-      usage
-      exit 1
+      warn "ERROR: Unknown format"
+      die 1 "$usage"
       break;;
   esac
 done
